all:
  children:
    linux:
      hosts:
        archlinux:
          ansible_host: archlinux.example.com
          ansible_user: your_initial_user
        debian:
          ansible_host: debian.example.com
          ansible_user: your_initial_user
        fedora:
          ansible_host: fedora.example.com
          ansible_user: your_initial_user
  vars:
    ansible_python_interpreter: /usr/bin/python3
